=== Java-Archive/rapidpm/base/conf/crawler_result_20100211.dtd
<!--
  ~ Copyright (c) since 2010
  ~ Dieses ist Bestandteil des NeoScio-Projektes und Eigentum der RapidPM - www.rapidpm.org (haftungsbeschraenkt)
  ~ Sven Ruppert : sven.ruppert@me.com
  ~ .
  -->

<!DOCTYPE documents [
        <!ELEMENT documents (document)*>
        <!ATTLIST documents
                timestamp CDATA #REQUIRED>
        <!ELEMENT document (doc_element)*>
        <!ATTLIST document
                uri CDATA #REQUIRED>
        <!ELEMENT doc_element (#PCDATA)>
        <!ATTLIST doc_element
                name CDATA #REQUIRED
                value CDATA #REQUIRED>
        ]>

=== Java-Archive/rapidpm/base/conf/CrawlerResultExample.xml
<!--
  ~ Copyright (c) since 2010
  ~ Dieses ist Bestandteil des NeoScio-Projektes und Eigentum der RapidPM - www.rapidpm.org (haftungsbeschraenkt)
  ~ Sven Ruppert : sven.ruppert@me.com
  ~ .
  -->

<!DOCTYPE documents SYSTEM "crawler_result_20100211.dtd">


<documents timestamp="">
    <document uri="">
        <doc_element status="" value=""/>
        <doc_element status="" value=""/>
        <doc_element status="" value=""/>
    </document>
    <document uri="">
        <doc_element status="" value=""/>
        <doc_element status="" value=""/>
        <doc_element status="" value=""/>
    </document>
    <document uri="">
        <doc_element status="" value=""/>
        <doc_element status="" value=""/>
        <doc_element status="" value=""/>
    </document>
</documents>
